### ISSUE TITLE
[Jest and Testing-Library] Feat Jest and Testing-Library package to run unit and integration tests

### ISSUE THREAD

**Issue by LucasAnselmoSilva12345** [LucasAnselmoSilva12345/John-Task-List#13]
## About this task

This task is responsible to adding jest and testing-library packages on the project and prepare the test environment.

### To-do

- [x] Adds Jest package
- [x] Adds Testing-Library package
- [x] Initial unit and integration test
