### ISSUE TITLE
[shadcn/UI] Feat shadcn/UI library 

### ISSUE THREAD

**Issue by LucasAnselmoSilva12345** [LucasAnselmoSilva12345/John-Task-List#14]
# About this task

This task is responsible to adding [shadcn/ui](https://ui.shadcn.com/) in the project.

## To-do task

- [x] Adding customize theme
- [x] Modo Toggle swicth theme
- [x] Label component
- [x] Input component
- [x] Button component
- [x] Adjust styles to following the Shadcn/UI's rules

**Comment by LucasAnselmoSilva12345** [comment]
[Commit about installed shadcn/ui library with custom theme](https://github.com/LucasAnselmoSilva12345/John-Task-List/commit/9cb3a42301a21ff08bc7cc7848c5fefb7fcc1f58)

**Comment by LucasAnselmoSilva12345** [comment]
To the task `Modo Toggle switch theme`, I'll remove the switch theme option in setting's modal.

![image](https://github.com/LucasAnselmoSilva12345/John-Task-List/assets/53938849/a0fa676a-cc05-4481-b1c5-2b0b5ab0b46d)


And adding the new switch theme option in the header component.

**Comment by LucasAnselmoSilva12345** [comment]
Use Button, Input and button component from the [shadcn/UI components](https://ui.shadcn.com/docs/components/accordion)

**Comment by LucasAnselmoSilva12345** [comment]
Adding the new sub-task, responsible to adjust the app styles.
